//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SicopService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sefaz.es.gov.br/nfpe", ConfigurationName="ServiceReference.WSSICOPImportacaoSoap")]
    public interface WSSICOPImportacaoSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sefaz.es.gov.br/nfpe/NfpeRecepcaoLote", ReplyAction="*")]
        System.Threading.Tasks.Task<SicopService.NfpeRecepcaoLoteResponse> NfpeRecepcaoLoteAsync(SicopService.NfpeRecepcaoLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sefaz.es.gov.br/nfpe/NfpeAnoBase", ReplyAction="*")]
        System.Threading.Tasks.Task<SicopService.NfpeAnoBaseResponse> NfpeAnoBaseAsync(SicopService.NfpeAnoBaseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NfpeRecepcaoLoteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NfpeRecepcaoLote", Namespace="http://www.sefaz.es.gov.br/nfpe", Order=0)]
        public SicopService.NfpeRecepcaoLoteRequestBody Body;
        
        public NfpeRecepcaoLoteRequest()
        {
        }
        
        public NfpeRecepcaoLoteRequest(SicopService.NfpeRecepcaoLoteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sefaz.es.gov.br/nfpe")]
    public partial class NfpeRecepcaoLoteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strNfpeDadosMsg;
        
        public NfpeRecepcaoLoteRequestBody()
        {
        }
        
        public NfpeRecepcaoLoteRequestBody(string strNfpeDadosMsg)
        {
            this.strNfpeDadosMsg = strNfpeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NfpeRecepcaoLoteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NfpeRecepcaoLoteResponse", Namespace="http://www.sefaz.es.gov.br/nfpe", Order=0)]
        public SicopService.NfpeRecepcaoLoteResponseBody Body;
        
        public NfpeRecepcaoLoteResponse()
        {
        }
        
        public NfpeRecepcaoLoteResponse(SicopService.NfpeRecepcaoLoteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sefaz.es.gov.br/nfpe")]
    public partial class NfpeRecepcaoLoteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NfpeRecepcaoLoteResult;
        
        public NfpeRecepcaoLoteResponseBody()
        {
        }
        
        public NfpeRecepcaoLoteResponseBody(string NfpeRecepcaoLoteResult)
        {
            this.NfpeRecepcaoLoteResult = NfpeRecepcaoLoteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NfpeAnoBaseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NfpeAnoBase", Namespace="http://www.sefaz.es.gov.br/nfpe", Order=0)]
        public SicopService.NfpeAnoBaseRequestBody Body;
        
        public NfpeAnoBaseRequest()
        {
        }
        
        public NfpeAnoBaseRequest(SicopService.NfpeAnoBaseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NfpeAnoBaseRequestBody
    {
        
        public NfpeAnoBaseRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NfpeAnoBaseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NfpeAnoBaseResponse", Namespace="http://www.sefaz.es.gov.br/nfpe", Order=0)]
        public SicopService.NfpeAnoBaseResponseBody Body;
        
        public NfpeAnoBaseResponse()
        {
        }
        
        public NfpeAnoBaseResponse(SicopService.NfpeAnoBaseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sefaz.es.gov.br/nfpe")]
    public partial class NfpeAnoBaseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NfpeAnoBaseResult;
        
        public NfpeAnoBaseResponseBody()
        {
        }
        
        public NfpeAnoBaseResponseBody(string NfpeAnoBaseResult)
        {
            this.NfpeAnoBaseResult = NfpeAnoBaseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public interface WSSICOPImportacaoSoapChannel : SicopService.WSSICOPImportacaoSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public partial class WSSICOPImportacaoSoapClient : System.ServiceModel.ClientBase<SicopService.WSSICOPImportacaoSoap>, SicopService.WSSICOPImportacaoSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSSICOPImportacaoSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WSSICOPImportacaoSoapClient.GetBindingForEndpoint(endpointConfiguration), WSSICOPImportacaoSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSSICOPImportacaoSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSSICOPImportacaoSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSSICOPImportacaoSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSSICOPImportacaoSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSSICOPImportacaoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SicopService.NfpeRecepcaoLoteResponse> SicopService.WSSICOPImportacaoSoap.NfpeRecepcaoLoteAsync(SicopService.NfpeRecepcaoLoteRequest request)
        {
            return base.Channel.NfpeRecepcaoLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SicopService.NfpeRecepcaoLoteResponse> NfpeRecepcaoLoteAsync(string strNfpeDadosMsg)
        {
            SicopService.NfpeRecepcaoLoteRequest inValue = new SicopService.NfpeRecepcaoLoteRequest();
            inValue.Body = new SicopService.NfpeRecepcaoLoteRequestBody();
            inValue.Body.strNfpeDadosMsg = strNfpeDadosMsg;
            return ((SicopService.WSSICOPImportacaoSoap)(this)).NfpeRecepcaoLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SicopService.NfpeAnoBaseResponse> SicopService.WSSICOPImportacaoSoap.NfpeAnoBaseAsync(SicopService.NfpeAnoBaseRequest request)
        {
            return base.Channel.NfpeAnoBaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<SicopService.NfpeAnoBaseResponse> NfpeAnoBaseAsync()
        {
            SicopService.NfpeAnoBaseRequest inValue = new SicopService.NfpeAnoBaseRequest();
            inValue.Body = new SicopService.NfpeAnoBaseRequestBody();
            return ((SicopService.WSSICOPImportacaoSoap)(this)).NfpeAnoBaseAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSSICOPImportacaoSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSSICOPImportacaoSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSSICOPImportacaoSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.sefaz.es.gov.br/wsSicopImportacao/WSSICOPImportacao.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSSICOPImportacaoSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.sefaz.es.gov.br/wsSicopImportacao/WSSICOPImportacao.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSSICOPImportacaoSoap,
            
            WSSICOPImportacaoSoap12,
        }
    }
}
